use test;
CREATE TABLE redefinicoes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  token VARCHAR(4) NOT NULL,
  expira DATETIME NOT NULL,
  criado_em DATETIME DEFAULT CURRENT_TIMESTAMP
);
